# Generated by Django 5.0.7 on 2024-07-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
