# Generated by Django 5.0.7 on 2024-07-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_about_us_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Category'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='food_bg',
            options={'verbose_name': 'Food Background', 'verbose_name_plural': 'Food Background'},
        ),
        migrations.AlterModelOptions(
            name='food_item',
            options={'verbose_name': 'Food Item', 'verbose_name_plural': 'Food Item'},
        ),
        migrations.AlterModelOptions(
            name='food_type',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quote'},
        ),
    ]
