# Generated by Django 5.0.7 on 2024-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_food_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='Get_in_touch',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
