# Generated by Django 5.0.7 on 2024-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservation'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='message',
        ),
        migrations.AddField(
            model_name='reservation',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
