# Generated by Django 5.0.7 on 2024-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_reservation_options_remove_reservation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.TextField(default='Please Call Back'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(max_length=50),
        ),
    ]
