# Generated by Django 5.0.7 on 2024-07-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_reservation_mobile_no_reservation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='occasion',
        ),
        migrations.AddField(
            model_name='reservation',
            name='occation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=7),
        ),
    ]
